# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 09:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190407_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': '博客表', 'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='blogs_type',
            options={'verbose_name': '博客类别表', 'verbose_name_plural': '博客类别表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_matter',
            field=tinymce.models.HTMLField(),
        ),
    ]
