# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190410_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_matter',
            field=tinymce.models.HTMLField(verbose_name='博客正文'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='博客标题'),
        ),
    ]
