# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190413_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='write_time',
            field=models.DateField(auto_now_add=True, verbose_name='发表时间'),
        ),
    ]
